language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y 'deb http://http.debian.net/debian stable main'
  - sudo add-apt-repository -y 'deb http://archive.ubuntu.com/ubuntu/ saucy main restricted'
  - sudo add-apt-repository -y 'ppa:zoogie/sdl2-snapshots'
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes libsdl-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl-net1.2-dev libphysfs-dev libglew-dev cppcheck
script: cmake . && make
after_script: cppcheck --verbose --enable=all --std=posix --std=c++11 --quiet `git ls-files source/\*.cpp`

